name: "Test Suite"
on:
  push:
  pull_request:

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate:
          - contracts/dice_token
          - contracts/randomness_oracle
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test --all-features
        working-directory: ${{ matrix.crate }}

  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate:
          - contracts/dice_token
          - contracts/randomness_oracle
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        run: cargo fmt -- --check
        working-directory: ${{ matrix.crate }}
