name: "Test Suite"
on:
  push:
  pull_request:

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Build dice_token wasm
        run: cargo build --target wasm32-unknown-unknown --release
        working-directory: contracts/dice_token

      - name: Build randomness_oracle wasm
        run: cargo build --target wasm32-unknown-unknown --release
        working-directory: contracts/randomness_oracle

      - name: Test dice_token
        run: cargo test --all-features
        working-directory: contracts/dice_token

      - name: Test randomness_oracle
        run: cargo test --all-features
        working-directory: contracts/randomness_oracle

      - name: Test dice_game
        run: cargo test --all-features
        working-directory: contracts/dice_game

  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate:
          - contracts/dice_token
          - contracts/randomness_oracle
          - contracts/dice_game
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        run: cargo fmt -- --check
        working-directory: ${{ matrix.crate }}
